### ISSUE TITLE
Renaming

### ISSUE THREAD

**Issue by schalkdaniel** [schalkdaniel/compboost#244]
- [x] Base-learner: `*Blearner -> Baselearner*` #249 
- [x] Loss: `*Loss -> Loss*` #250
- [x] Logger: `*Logger -> Logger*` #251
- [x] Optimizer: `* -> Optimizer*` #248 
- [x] Getter:
    - [x] Inbag Risk: `getInbagRisk()` #245 
    - [x] Estimated Coefficients: `getEstimatedCoef()` #247 
    - [x] Selected learner: `getSelectedBaselearner()` #246

**Comment by schalkdaniel** [comment]
Should be fine now, PRs are above.
